"""
Browser Testing Agent for Jarvis v2
Tests generated web pages to verify they render correctly.
Uses Playwright for headless browser automation.
"""
import os
import subprocess
import json
from datetime import datetime
from typing import Dict, List, Optional
from .config import WORKSPACE_DIR


class BrowserTester:
    """
    Tests web pages generated by the autonomous executor.
    
    Features:
    - Open HTML files in browser
    - Take screenshots for verification
    - Check for console errors
    - Verify elements exist
    - Mobile/desktop viewport testing
    """
    
    def __init__(self):
        self.screenshots_dir = os.path.join(WORKSPACE_DIR, "screenshots")
        os.makedirs(self.screenshots_dir, exist_ok=True)
        self._playwright_installed = None
    
    def test_page(self, file_path: str, checks: List[str] = None) -> Dict:
        """
        Test a web page.
        
        Args:
            file_path: Path to HTML file or URL
            checks: Optional list of CSS selectors to verify exist
            
        Returns:
            Dict with test results, screenshot path, and any errors
        """
        result = {
            "file": file_path,
            "timestamp": datetime.now().isoformat(),
            "success": False,
            "screenshot": None,
            "console_errors": [],
            "element_checks": [],
            "viewport_tests": [],
            "load_time_ms": 0
        }
        
        # Determine if it's a file or URL
        if file_path.startswith(("http://", "https://")):
            url = file_path
        elif os.path.exists(file_path):
            url = f"file:///{file_path.replace(os.sep, '/')}"
        else:
            result["error"] = f"File not found: {file_path}"
            return result
        
        # Use Python's webbrowser for simple test, or Playwright if available
        if self._check_playwright():
            return self._test_with_playwright(url, checks, result)
        else:
            return self._test_simple(url, result)
    
    def _test_simple(self, url: str, result: Dict) -> Dict:
        """Simple browser test using Python http.server."""
        import webbrowser
        
        try:
            # Just open in default browser
            webbrowser.open(url)
            result["success"] = True
            result["note"] = "Opened in default browser. Install playwright for advanced testing."
        except Exception as e:
            result["error"] = str(e)
        
        return result
    
    def _test_with_playwright(self, url: str, checks: List[str], result: Dict) -> Dict:
        """Full browser test using Playwright."""
        try:
            from playwright.sync_api import sync_playwright
        except ImportError:
            result["error"] = "Playwright not installed. Run: pip install playwright && playwright install"
            return result
        
        try:
            with sync_playwright() as p:
                browser = p.chromium.launch(headless=True)
                
                # Desktop viewport test
                page = browser.new_page(viewport={"width": 1920, "height": 1080})
                
                # Capture console errors
                console_errors = []
                page.on("console", lambda msg: console_errors.append(msg.text) if msg.type == "error" else None)
                
                # Load page and measure time
                start = datetime.now()
                page.goto(url, wait_until="networkidle")
                load_time = (datetime.now() - start).total_seconds() * 1000
                
                result["load_time_ms"] = round(load_time, 2)
                result["console_errors"] = console_errors
                
                # Take desktop screenshot
                screenshot_name = f"test_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
                screenshot_path = os.path.join(self.screenshots_dir, screenshot_name)
                page.screenshot(path=screenshot_path, full_page=True)
                result["screenshot"] = screenshot_path
                
                # Check elements exist
                if checks:
                    for selector in checks:
                        try:
                            element = page.query_selector(selector)
                            result["element_checks"].append({
                                "selector": selector,
                                "found": element is not None
                            })
                        except:
                            result["element_checks"].append({
                                "selector": selector,
                                "found": False,
                                "error": "Invalid selector"
                            })
                
                # Mobile viewport test
                page.set_viewport_size({"width": 375, "height": 667})
                page.reload(wait_until="networkidle")
                
                mobile_screenshot_name = f"test_mobile_{datetime.now().strftime('%Y%m%d_%H%M%S')}.png"
                mobile_screenshot_path = os.path.join(self.screenshots_dir, mobile_screenshot_name)
                page.screenshot(path=mobile_screenshot_path, full_page=True)
                
                result["viewport_tests"].append({
                    "viewport": "mobile (375x667)",
                    "screenshot": mobile_screenshot_path
                })
                
                browser.close()
                
                # Determine overall success
                result["success"] = len(console_errors) == 0 and all(
                    check.get("found", False) for check in result.get("element_checks", [])
                )
                
        except Exception as e:
            result["error"] = str(e)
        
        return result
    
    def _check_playwright(self) -> bool:
        """Check if Playwright is installed."""
        if self._playwright_installed is not None:
            return self._playwright_installed
        
        try:
            import playwright
            self._playwright_installed = True
        except ImportError:
            self._playwright_installed = False
        
        return self._playwright_installed
    
    def test_project(self, project_path: str) -> Dict:
        """
        Test all HTML files in a project.
        
        Args:
            project_path: Path to project directory
            
        Returns:
            Dict with results for each HTML file
        """
        results = {
            "project": project_path,
            "timestamp": datetime.now().isoformat(),
            "files_tested": [],
            "passed": 0,
            "failed": 0
        }
        
        # Find all HTML files
        for root, dirs, files in os.walk(project_path):
            dirs[:] = [d for d in dirs if not d.startswith('.') and d != 'node_modules']
            
            for file in files:
                if file.endswith('.html'):
                    full_path = os.path.join(root, file)
                    
                    test_result = self.test_page(full_path)
                    results["files_tested"].append(test_result)
                    
                    if test_result.get("success"):
                        results["passed"] += 1
                    else:
                        results["failed"] += 1
        
        # Save results
        self._save_results(project_path, results)
        
        return results
    
    def _save_results(self, project_path: str, results: Dict):
        """Save test results to project."""
        jarvis_dir = os.path.join(project_path, ".jarvis")
        os.makedirs(jarvis_dir, exist_ok=True)
        
        results_path = os.path.join(jarvis_dir, "browser_tests.json")
        with open(results_path, 'w', encoding='utf-8') as f:
            json.dump(results, f, indent=2)
    
    def quick_preview(self, file_path: str) -> bool:
        """
        Quick preview - just open in browser.
        
        Args:
            file_path: Path to HTML file
            
        Returns:
            True if opened successfully
        """
        import webbrowser
        
        if os.path.exists(file_path):
            url = f"file:///{file_path.replace(os.sep, '/')}"
            webbrowser.open(url)
            return True
        return False
    
    def start_dev_server(self, project_path: str, port: int = 8000) -> Dict:
        """
        Start a simple HTTP server for the project.
        
        Args:
            project_path: Path to serve
            port: Port number
            
        Returns:
            Dict with server info
        """
        import threading
        import http.server
        import socketserver
        
        # Find the src directory or use project root
        serve_dir = os.path.join(project_path, "src")
        if not os.path.exists(serve_dir):
            serve_dir = project_path
        
        class Handler(http.server.SimpleHTTPRequestHandler):
            def __init__(self, *args, **kwargs):
                super().__init__(*args, directory=serve_dir, **kwargs)
        
        try:
            with socketserver.TCPServer(("", port), Handler) as httpd:
                url = f"http://localhost:{port}"
                
                # Open in browser
                import webbrowser
                webbrowser.open(url)
                
                return {
                    "success": True,
                    "url": url,
                    "serving": serve_dir,
                    "port": port
                }
        except Exception as e:
            return {
                "success": False,
                "error": str(e)
            }


# Singleton
browser_tester = BrowserTester()
